version: "3"

services:
  webserver:
    build:
      context: ./docker/apache
    container_name: 'sx-server'
    restart: always
    ports:
      - "80:80"
      - "443:443"
    links:
      - mysql
    volumes:
      - ${DOCUMENT_ROOT-./www}:/var/www/html
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini
      - ${APACHE_DIR-./config/apache}:/etc/apache2/sites-enabled
      - ${LOG_DIR-./logs/apache}:/var/log/apache2
  mysql:
    build: ./docker/mysql
    container_name: 'sx-sql'
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: regsecret
      MYSQL_USER: john
      MYSQL_PASSWORD: doe
      MYSQL_DATABASE: box
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'sx-phpmyadmin'
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - '704:80'
    volumes:
      - /sessions
  redis:
    container_name: 'sx-redis'
    image: redis:latest
    ports:
      - "6379:6379"

      
